# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-21 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data1', models.TextField()),
                ('data2', models.TextField()),
                ('data3', models.TextField()),
                ('valid', models.BooleanField(default=False, editable=False)),
                ('datechange', models.DateTimeField(auto_now=True)),
                ('datesync', models.DateTimeField(editable=False)),
                ('syncstatus', models.IntegerField(choices=[(1, 'new'), (2, 'updated'), (3, 'upd_sync'), (4, 'upd_synced'), (5, 'ok'), (6, 'mark_to_del'), (7, 'deleted'), (8, 'error'), (9, 'collision')], default=1)),
                ('version', models.PositiveIntegerField(default=1)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
